import { Game } from '@/entities/game/model/types'

export const games: Game[] = [
  {
    id: 'memory-match',
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Memorize and reproduce sequences of colorful tiles.',
    status: 'available',
    category: 'memory',
    difficulty: 'easy',
    duration: '3–5 min',
    color: '#FACC15',
    iconUrl: 'https://api.iconify.design/lucide:brain.svg',
  },
  {
    id: 'reaction-test',
    slug: 'reaction-test',
    title: 'Reaction Test',
    description: 'How fast are your reflexes?',
    status: 'available',
    category: 'reaction',
    difficulty: 'easy',
    duration: '1–2 min',
    color: '#A78BFA',
    iconUrl: 'https://api.iconify.design/lucide:zap.svg',
  },
  {
    id: 'sudoku-blitz',
    slug: 'sudoku-blitz',
    title: 'Sudoku Blitz',
    description: 'Fast-paced 6x6 sudoku puzzles against the clock.',
    status: 'available',
    category: 'logic',
    difficulty: 'medium',
    duration: '5–10 min',
    color: '#34D399',
    iconUrl: 'https://api.iconify.design/lucide:grid-3x3.svg',
  },
  {
    id: 'word-chain',
    slug: 'word-chain',
    title: 'Word Chain',
    description: 'Build the longest chain of connected words before time runs out.',
    status: 'coming-soon',
    category: 'word',
    difficulty: 'medium',
    duration: '3–5 min',
    color: '#F472B6',
    iconUrl: 'https://api.iconify.design/lucide:type.svg',
  },
  {
    id: 'target-practice',
    slug: 'target-practice',
    title: 'Target Practice',
    description: 'Hit as many moving targets as you can in 60 seconds.',
    status: 'coming-soon',
    category: 'reaction',
    difficulty: 'hard',
    duration: '1 min',
    color: '#FB923C',
    iconUrl: 'https://api.iconify.design/lucide:crosshair.svg',
  },
]
